#!/usr/bin/env bash

# Detectar monitor enfocado y devolver la ruta de config
monitor=$(hyprctl -j monitors | jq -r '.[] | select(.focused==true) | .name')
echo "$HOME/.config/rofi/configs/smallconfig.rasi"
