#!/usr/bin/env bash

# Configuración Rofi
ROFI_CONFIG="$(~/.config/rofi/scripts/detect-monitor)"

# Opciones del menú
options=" Power Off\n Reboot\n󰍃 Logout\n Block"

# Mostrar menú
choice=$(echo -e "$options" | rofi -dmenu -p "Power" -config "$ROFI_CONFIG")

# Ejecutar acción según elección
case "$choice" in
    " Power Off")
        ~/.config/rofi/scripts/rofi-confirm \
        "Do you want to power off?" \
        "systemctl poweroff"
        ;;
    " Reboot")
        ~/.config/rofi/scripts/rofi-confirm \
        "Do you want to reboot the system?" \
        "systemctl reboot"
        ;;
    "󰍃 Logout")
        ~/.config/rofi/scripts/rofi-confirm \
        "Do you want to close the session?" \
        "hyprctl dispatch exit"
        ;;
    " Block")
        hyprlock
        ;;
esac
