#!/usr/bin/env bash

# Configuración Rofi
ROFI_CONFIG="$(~/.config/rofi/scripts/detect-monitor)"

# Opciones del menú
options=" Suspender\n Apagar\n Reiniciar\n Bloquear"

# Mostrar menú
choice=$(echo -e "$options" | rofi -dmenu -p "Power" -config "$ROFI_CONFIG")

# Ejecutar acción según elección
case "$choice" in
    " Suspender")
        systemctl suspend
        ;;
    " Apagar")
        systemctl poweroff
        ;;
    " Reiniciar")
        systemctl reboot
        ;;
    " Bloquear")
        # Dependiendo del lockscreen que uses
        swaylock -f
        ;;
esac
